language: node_js

node_js:
  - "10"
  - "11"
  - "12"
  - "node"

before_script:
  - yarn build

after_success:
  - yarn coverage
  - test $TRAVIS_NODE_VERSION = 12 && yarn coveralls

notifications:
    email: false

deploy:
  provider: npm
  skip_cleanup: true
  email: hi@thorgate.eu
  api_key:
    secure: >
      lU4A8xmAANiiaNwfPCDVA1QKAyPxOG8l/NPdA0eaOVxdJSyuVVcQbJehxmrnnshZze7usCnzc02PGVjN467GWTF3SMwbJ
      l9SyToXgn0mgNLjB3s+bfaGjEwwBJtLQD4bBwTnC7qZKBXjqvGjBPZXpQfs7tr5toGkb9CDxG3tLrrdjGhzcF5sKprSmb
      7n7vp9EbD9U04kiYnGUOuGInb0qALEOZjJKmX4xQplotH2NUsgt5NG7+FQ59Fa/kyqOvAOXMCnYK1ulNjHxagkqDHasCK
      VS6QMEJJvYCwYObFKem598Pjf+w6ev2LuNQO+ILDs1enHRb8XEjLsLNVDWt+NzA0Gaw6ABjkQy3zYIGVu0zVNygx24vOX
      QB8yuM+4WEJkxMpLCVLGziYm3vY3VZoUiFSDK1TmTKmOIiJFBfqHnb14Q+eYU5OmuU4O/C0W0mL1NaxSACbJZEzRmqaS8
      QlWMfZ+YWOuZI5zYAFu7DUwwCn97RWQ95CyWe8TreHXD8qOZaJ2zteibUrDiKCSMCVMmcUhHemTs5alRiATn46j+b2ngf
      3qBCaAjM24DE8a0yb8K6WVityNiy/0peUi7SfqZoVZ7whkbdGGpmrAHRzsDwxKvxVismy5PxUtWuQfreh8Udy+JB1huKx
      gTrPnUhYcBAADOitN1OmORx6/e9hLY1k=
  on:
    tags: true
    node: "12"
